import { z } from "zod";

export const appDataSchema = z.object({});

export const appKeysSchema = z.object({
  video_room_client_1: z.string(),
  video_room_client_2: z.string(),
  video_room_client_3: z.string(),
  video_room_client_4: z.string(),
  video_room_client_5: z.string(),
  video_room_client_6: z.string(),
  video_room_client_7: z.string(),
  video_room_client_8: z.string(),
  video_room_client_9: z.string(),
  video_room_client_10: z.string(),
  video_room_client_11: z.string(),
  video_room_client_12: z.string(),
  video_room_client_13: z.string(),
  video_room_client_14: z.string(),
  video_room_client_15: z.string(),
  video_room_client_16: z.string(),
  video_room_client_17: z.string(),
  video_room_client_18: z.string(),
  video_room_client_19: z.string(),
  video_room_client_20: z.string(),
  video_room_client_21: z.string(),
  video_room_client_22: z.string(),
  video_room_client_23: z.string(),
  video_room_client_24: z.string(),
  video_room_client_25: z.string(),
  video_room_client_26: z.string(),
  video_room_client_27: z.string(),
  video_room_client_28: z.string(),
  video_room_client_29: z.string(),
  video_room_client_30: z.string(),
  video_room_client_31: z.string(),
  video_room_client_32: z.string(),
  video_room_client_33: z.string(),
  video_room_client_34: z.string(),
  video_room_client_35: z.string(),
  video_room_client_36: z.string(),
  video_room_client_37: z.string(),
  video_room_client_38: z.string(),
  video_room_client_39: z.string(),
  video_room_client_40: z.string(),
  video_room_client_41: z.string(),
  video_room_client_42: z.string(),
  video_room_client_43: z.string(),
  video_room_client_44: z.string(),
  video_room_client_45: z.string(),
  video_room_client_46: z.string(),
  video_room_client_47: z.string(),
  video_room_client_48: z.string(),
  video_room_client_49: z.string(),
  video_room_client_50: z.string(),
});
